### ISSUE TITLE
Not working in mid-print: extruder dead

### ISSUE THREAD

**Issue by FreifunkerEZ** [jim-p/Change_Filament#13]
Hellows!

Thanks for the nice plugin.

Maybe it's an understanding problem of mine. I sometimes change the color of the filament during prints. I did so manually before and simply hit pause. But that caused filament to continue to ooze onto the print, which was not nice. Here comes the change filament plugin! yay! But it did not work as I expected:

* In mid-print I changed the settings, and they did not seem to take. I set load speed and distance to the same as unload-speed and distance but it did not take. It loaded very slowly and only the short distance. I have a delta, so I need to pump the filament through the bowden-tube. But I fixed that by manually pushing and wanted to continue to print. 
* But the head did not move back from the park position. Okay, It was a clean 30mm so I moved it with the controls 3x 10mm.
* Then I hit resume and while the printhead started to move, there was no extrusion. When I tried to turn the extruder manually, I noticed that the driver had shut down and I was free to turn the knob.

I guess I'm using it wrong. Can you please comment?

**Comment by jim-p** [comment]
* You have to refresh the whole page in your browser after changing settings, or the old values will still be in use
* There is no code to store the old position, it only parks, it does not return automatically.
* When unloading, the extruder stepper is disabled, but when loading it is run again, so it should be re-enabled automatically by the extrude command it performs then. It's possible your firmware does something unexpected here.

If your printer firmware supports it, using M600 is better to do mid-print.
