### ISSUE TITLE
Compatibility with Temeify - Change to Temp tab

### ISSUE THREAD

**Issue by ErSedavi** [jim-p/Change_Filament#14]
Hi,
First of all, I love your plugin, it's easier to use than my Ender 3's default method, but I have 2 requests.
1- I have a problem using your plugin with Temeify that doesn't show the icons correctly. It doesn't bother me a lot, I can keep using it perfectly.

![Change_filament](https://user-images.githubusercontent.com/51030864/68088627-45edb580-fe61-11e9-8185-43cfccf968ba.JPG)

2- Is it possible to move the buttons to the temperature tab? I think it would make easier and more intuitive to preheat and change the filament.

Thanks.

**Comment by jim-p** [comment]
1- That is a problem in Themeify, see #4 -- I have tried alternate ways to render the buttons but none worked so far.
2- Not that I am aware of. Not without completely redesigning it from the ground up using much more complicated methods.
