### ISSUE TITLE
Fail to resume correctly

### ISSUE THREAD

**Issue by user100000** [jim-p/Change_Filament#20]
Marlin 2.o on ender-3 using  skr e3 mini  using Version 1.4.0.

on clicking the   park button  the  Nozzle lifts and safe homes, at 0,0 and a height  incrase of  Z . It then resumes print  at x,y ,Z  without  any futher action by the user.

**Comment by jim-p** [comment]
The park button and such is not meant to be used mid-print. Use the M600 button for that. There is no way for this plugin to store and return to the original coordinates when manually parking.
