### ISSUE TITLE
Two buttons blank

### ISSUE THREAD

**Issue by EddyMI3d** [jim-p/Change_Filament#22]
Nice plugin, but the two left buttons are blank with my installation.
![grafik](https://user-images.githubusercontent.com/8533327/81072065-e17de280-8ee5-11ea-93eb-198d5341834b.png)

Running OctoPi 0.17.0, OctoPrint 1.4.0, Change Filament 0.3.1

**Comment by jim-p** [comment]
What other plugins are you using? Last time that came up, it was from the Themeify plugin, but it could also be something else in your browser.

**Comment by EddyMI3d** [comment]
Thanks for that hint, it's actually Themeify that troubles.

**Comment by jim-p** [comment]
OK -- So it's the same as #8

Themeify needs to fix that glitch, nothing I can change in the code here can help that.
