### ISSUE TITLE
transfer the display of buttons to a tab with temperature

### ISSUE THREAD

**Issue by ssavickiy** [jim-p/Change_Filament#23]
it is more logical to transfer the display of buttons to a tab with temperature, or add an option to choose which tab to display
![image](https://user-images.githubusercontent.com/23532871/82755693-f7444080-9ddd-11ea-9935-629e3051d1f4.png)

**Comment by jim-p** [comment]
I looked into that initially but the current plugin API doesn't have a way to do that easily.
